### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ultraviolets369** [INFO-526-SU24/final-project-manasppanse#1]
The following is the peer review of the project proposal by Violeta Keifer. The team members that participated in this review are :

- [Violeta Keifer] - @[ultraviolets369]

- Describe the goal of the project.
The goal of this project is to understand number of objects deployed into space over time from 1957 to 2023. It also aims to determine which countries deploy objects into space over time.

- Describe the data used or collected.
This project will involve data on outer space objects. This data set includes the country that deployed the object, the year it was deployed, and how many objects were deployed.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
For the first question, the variables of year and number of objects will be used to create a time series plot to see how deployment of objects varies over time. For the second question, a time series of objects by country will be created.

- Is there anything that is unclear from the proposal?

The goals and analysis plan are clear. The plan of attack is very thorough and shows each step they will take to accomplish their goals.

- Provide constructive feedback on how the team might be able to improve their project.

The two proposed plots are very similar as both will be time series. While the time series by country will be interesting, I wonder if there is a way to display information for the second question in a visual way with number of objects sent into space by country displayed on a map for selected years.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

I am very interested to see the time series plots and what trends exist in how often countries send objects into space. I almost chose this data set for my own project so I am very excited to see what information it holds.

- Provide constructive feedback on any issues with file and/or code organization.
Files are organized well.. Data is located in the data folder. I did not have any issues with rendering the proposal locally.

- (Optional) Any further comments or feedback?

Great work outlining your plan of attack! It is clear you know what you are doing and I look forward to your final project!

**Comment by manasppanse** [comment]
"The two proposed plots are very similar as both will be time series. While the time series by country will be interesting, I wonder if there is a way to display information for the second question in a visual way with number of objects sent into space by country displayed on a map for selected years."
---> Based on this feedback, I've made the necessary changes.

Thanks for your valuable feedback @ultraviolets369 !!! I hope you like the final project. And all the best for yours.
