### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by CristinaUAMS** [INFO-526-SU24/final-project-manasppanse#2]
The following is the peer review of the project proposal by CristinaUAMS. 
The team members that participated in this review are 
- _Cristina Lafuente - @CristinaUAMS_ 

- **Goal of the Project**
    The intention of this project is to examine the number of objects observed in space over time and the how countries reporting outer space objects has changed over time.

- **Data used or collected**
   The data comes from the set "outer_space_objects.csv" - presumably this is one of the TidyTuesday datasets though it appears that the exact citing may be missing from the proposal wording.

- **Description of how the research question will be answered, e.g. what approaches / methods will be used.**
    The research questions will be answered by plotting the number of objects over time, for the second question, they will add to that grouping by different countries to get the answer to the second question.

- **Anything that is unclear from the proposal.**
    The proposal and questions use the word "observed," and "recorded," whereas the TidyTuesday [description](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-04-23/readme.md) of the data says that these are objects launched by the noted countries. Perhaps wording is the issue. 

- **Constructive feedback on how the team might improve their project**
  While not completely overlapping, the two questions are very nearly the same and use very nearly the same variables. I think that it might be more interesting to see not only what countries are contributing more objects as one question but as the other, perhaps to see trends in type of launched objects over time or a variety of other questions answered. How does a country's launched objects change as they engage in world conflicts? So many cool questions that could be answered by bringing in other datasets as well.

- **Aspect of this project are you most interested in and would like to see highlighted in the presentation.**
    I am most interested to see the differences in launches by country over time.

- **Constructive feedback on any issues with file and/or code organization.**
    There are some minor coding convention violations such as in the p_load each package should have its own line, other than that, everything is well organized.

- **(Optional) Any further comments or feedback?**
    Super detailed plan of attack!

**Comment by manasppanse** [comment]
"The proposal and questions use the word "observed," and "recorded," whereas the TidyTuesday [description](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-04-23/readme.md) of the data says that these are objects launched by the noted countries. Perhaps wording is the issue."
---> Hi Cristina, you know, sometimes my brain happens to evolve backwards 😂. I realized my mistake and have made the changes accordingly.

"While not completely overlapping, the two questions are very nearly the same and use very nearly the same variables. I think that it might be more interesting to see not only what countries are contributing more objects as one question but as the other, perhaps to see trends in type of launched objects over time or a variety of other questions answered. How does a country's launched objects change as they engage in world conflicts? So many cool questions that could be answered by bringing in other datasets as well."
---> Based on this feedback, I've made the necessary changes as outlined in the first review as well.

Thanks for your valuable feedback @CristinaUAMS !!! I hope you like the final project. And all the best for yours.

**Comment by manasppanse** [comment]
Also, "There are some minor coding convention violations such as in the p_load each package should have its own line, other than that, everything is well organized."
---> Sorry Cristina, but I don't agree with you on this. The pacman::p_load function is designed to load multiple packages at once in a single line for convenience. Loading packages on multiple lines or a single line is completely a personal or team preference. So as far as my knowledge goes, this is not a violation and hence, I won't be making any changes to this.
